kind: Task
apiVersion: tekton.dev/v1
metadata:
  name: jumpstarter-setup-client
spec:
  description: |
    Setup Jumpstarter client config
  params:
    - name: endpoint
      description: "The Jumpstarter grpc endpoint"
      type: string
    - name: namespace
      description: "The Jumpstarter client namespace"
      type: string
    - name: name
      description: "The Jumpstarter client name"
      type: string
  steps:
    - name: setup-client
      image: docker.io/library/fedora:41
      script: |
        #!/usr/bin/env bash

        set -euo pipefail

        CONFIG_DIR=$(workspaces.config-dir.path)

        # create jumpstarter client config directories
        mkdir -p ${CONFIG_DIR}/clients/

        # generate jumpstarter user config
        cat > ${CONFIG_DIR}/config.yaml <<EOF
        apiVersion: jumpstarter.dev/v1alpha1
        kind: UserConfig
        config:
          current-client: default
        EOF

        # generate jumpstarter client config
        cat > ${CONFIG_DIR}/clients/default.yaml <<EOF
        apiVersion: jumpstarter.dev/v1alpha1
        kind: ClientConfig
        metadata:
          namespace: $(params.namespace)
          name: $(params.name)
        endpoint: $(params.endpoint)
        token: `cat /var/run/secrets/kubernetes.io/serviceaccount/token`
        drivers:
          allow: []
          unsafe: True
        EOF
  workspaces:
    - name: config-dir
      description: The workspace which contains Jumpstarter client config
