---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: noop
spec:
  description: Nothing to do
  params:
    - name: EXTRA_CMD
      type: string
      default: ""
  steps:
    - name: noop
      image: registry.redhat.io/ubi9/python-312

      script: |
        #!/usr/bin/env bash
        
        set -euxo pipefail

        pwd

        ls -la

        $(params.EXTRA_CMD)

      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source